### ISSUE TITLE
Adopt shell scripts

### ISSUE THREAD

**Issue by Bouncner** [hpi-epic/pricewars-analytics#1]
We should make the shell script aware of both possible standard installations: (i) docker and (ii) HPI-VM setup.

Thus, we should check for the two paths of kafka/flink (e.g., via `[ -x ...kafka ]` and use these accordingly throughout the scripts.

**Comment by MrSerth** [comment]
Regarding the docker setup: Of course, we may delete the topics similar to the way it is currently done in the script. Additionally, it is possible to stop the containers, remove the corresponding folder from the docker-mounts directory and restart the container. Just as a side note.

**Comment by Bouncner** [comment]
I'd prefer the script solution since it is much faster (depending on what you do with the platform you might want to delete the flink jobs pretty often) and it works with any setup, not just the docker one.

**Comment by MrSerth** [comment]
Yes, for sure. I fully agree

**Comment by Bouncner** [comment]
Since the docker setup is our main distribution goal for the longer term, I'll fix the paths to /opt/flink and /opt/kafka.
If anybody intends to install the component on a stand alone server, it should be straightforward to recognize that a `ln -s /opt/ ...` is required.

**Comment by Bouncner** [comment]
Commit a432bd4c887c7ef613856c1aca8e9b6d5a826260 closes #1
